### PR TITLE
Fix repository url in `package.json`

### PR DESCRIPTION
**Pull request by fyockm**
`git` vs `https` doesn't matter so much, but needs to have full username for @HenrikJoreteg

### CODE REVIEW

**Comment by mhamann** [comment]
Looks good. Thanks for the update.

**Comment by mhamann** [comment]
Update is live on npm.

**Comment by fyockm** [comment]
:+1:  thanks @mhamann

**Comment by HenrikJoreteg** [comment]
+1 thanks :)

**Pull request merged**
